version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
      - sql_data:/var/opt/mssql
    environment:
      TZ: Asia/Shanghai
      ACCEPT_EULA: "Y"
      SA_PASSWORD: My.Password
      MSSQL_COLLATION: Chinese_PRC_CI_AS
volumes:
  sql_data: {}
